name: Deploy to staging 
on: push:
branches: - "main"

jobs:
redeploy_everything:
name:Deploying everthing to the staging cluster

steps:
-name: SSH Into server
-run:
echo {{secrets.SSH_PRIVATE_KEY}} &>  ~/ssh_key
ssh -i ~/.ssh-key root@64.227.147.124
cd week-25-ci-next-app/ && git pull
pnpm install
pnpm run build
pm2 restart fe-server
pm2 restart http-server
pm2 restart ws-server